version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: |
          dotnet build
          dotnet test
          dotnet publish -c Release
      - setup_remote_docker
      - run: docker build -t dkuwahara/d2ng:$CIRCLE_BRANCH .
