version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet publish -c Release
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: dotnet test
  build_docker:
    machine: true
    steps:
      - run: docker build -t dkuwahara/d2ng:local .
  push_docker:
    machine: true
    steps:
      - run: | 
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t dkuwahara/d2ng:$TAG
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push dkuwahara/d2ng:$TAG
 
workflows:
  version: 2
  build-test-and-docker:
    jobs:
      - build
      - test:
          requires:
            - build
      - build_docker:
          requires:
            - build
          filters:
            branches:
              ignore: 
                - master
      - push_docker:
          requires:
            - build
          filters:
            branches:
              only: master